### ISSUE TITLE
[1.16.5] Mod Loading has failed

### ISSUE THREAD

**Issue by speccycy** [KaiKikuchi/ServerRedirect#17]
Can't start game
game crash

Java 8
forge-1.16.5-36.2.35
ServerRedirect-ForgeMC16-1.4.4a

**mods:**
BiomesOPlenty-1.16.5-13.1.0.486-universal
CustomNPCs-1.16.5.20220525snapshot
OptiFine_1.16.5_HD_U_G8
Pixelmon-1.16.5-9.0.0-universal
ServerRedirect-ForgeMC16-1.4.4a

```
java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:71) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:174) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.35.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
```

**Comment by Brend-Smits** [comment]
Does the crash also happen without ServerRedirect?

**Comment by KaiKikuchi** [comment]
Server Redirect does not do anything at game start, but only when the /redirect command is used. I know for certain that Server Redirect has been tested with Pixelmon Reforged 9 because I am in contact with the reforged team and they tested Server Redirect with their mod, as they have a modpack with it.

Please post the entire crash log file, not just this exception stack trace that does not mention Server Redirect in any part of it!

**Comment by speccycy** [comment]
oh my bad
There is already a ServerRedirect mod in Pixelmon.

sorry

**Comment by KaiKikuchi** [comment]
No problem, I was going to mention that they included Server Redirect in the mod itself, so you cannot add Server Redirect separately!
