### ISSUE TITLE
In some platforms, it will flash back when the client connection is customized

### ISSUE THREAD

**Issue by andjie98** [KaiKikuchi/ServerRedirect#18]
[17:52:17] [Receiver/INFO] [com.netease.mc.mod.network.message.reply.Reply]: [Network] java.lang.String 1 /serverredirect * 123
[17:52:17] [Sender/INFO] [com.netease.mc.mod.network.common.Common]: [ME]: 
[17:52:17] [Sender/INFO] [com.netease.mc.mod.network.common.Common]: 18  5  
[17:52:17] [Receiver/INFO] [com.netease.mc.mod.network.common.Common]: [SERVER]: 
[17:52:17] [Receiver/INFO] [com.netease.mc.mod.network.common.Common]: 18  5  
[17:52:17] [Receiver/INFO] [com.netease.mc.mod.network.common.Common]: smid:4613
[17:52:17] [Receiver/INFO] [com.netease.mc.mod.network.message.reply.Reply]: [Network] boolean 0 false
[17:52:17] [Receiver/INFO] [com.netease.mc.mod.network.message.reply.Reply]: [Network] long 1 0
[17:52:17] [Receiver/INFO] [com.netease.mc.mod.network.message.reply.Reply]: [Network] long 2 1
[17:52:17] [main/INFO] [com.netease.mc.mod.network.common.Common]: open screen : null
[17:52:17] [main/INFO] [com.netease.mc.mod.network.common.Common]: open screen : null
[17:52:17] [main/INFO] [net.kaikk.mc.serverredirect.forge.ServerRedirect]: Connecting to 123
[17:52:17] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: shaojie98 lost connection: 连接中止
[17:52:17] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: shaojie98退出了游戏
[17:52:17] [Server thread/INFO] [com.netease.mc.mod.network.common.Common]: TextComponent{text='', siblings=[TextComponent{text='shaojie98', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg shaojie98 '}, hoverEvent=HoverEvent{action=SHOW_ENTITY, value='TextComponent{text='{name:"shaojie98",id:"f376ea64-a367-4bb3-bb67-76642145b5f6"}', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}'}, insertion=shaojie98}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg shaojie98 '}, hoverEvent=HoverEvent{action=SHOW_ENTITY, value='TextComponent{text='{name:"shaojie98",id:"f376ea64-a367-4bb3-bb67-76642145b5f6"}', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}'}, insertion=shaojie98}}/local:E:8cc05738 logout
[17:52:17] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Stopping singleplayer server as player logged out
[17:52:17] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[17:52:17] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[17:52:17] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[17:52:17] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'shaojie98的世界20'/overworld
[17:52:17] [Server thread/INFO] [FML]: Unloading dimension 0
[17:52:18] [Server thread/INFO] [FML]: Applying holder lookups
[17:52:18] [Server thread/INFO] [FML]: Holder lookups applied
[17:52:19] [main/INFO] [com.netease.mc.mod.network.common.Common]: open screennet.minecraft.client.gui.GuiMultiplayer
[17:52:19] [main/INFO] [com.netease.mc.mod.network.common.Common]: init screennet.minecraft.client.gui.GuiMultiplayer
[17:52:19] [main/INFO] [com.netease.mc.mod.network.common.Common]: init screennet.minecraft.client.gui.GuiMultiplayer
[17:52:19] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: net.minecraft.util.MinecraftError
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1087) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:172) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-1.12.jar:?]
Caused by: net.minecraft.util.MinecraftError
	at net.minecraft.client.LoadingScreenRenderer.func_73722_d(LoadingScreenRenderer.java:55) ~[bie.class:?]
	at net.minecraft.client.LoadingScreenRenderer.func_73721_b(LoadingScreenRenderer.java:38) ~[bie.class:?]
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2473) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2429) ~[bib.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting.<init>(GuiConnecting.java:38) ~[bkr.class:?]
	at net.kaikk.mc.serverredirect.forge.ServerRedirect.redirect(ServerRedirect.java:125) ~[ServerRedirect.class:1.4.4]
	at net.kaikk.mc.serverredirect.forge.PacketHandler.lambda$onRedirectAddressMessage$0(PacketHandler.java:28) ~[PacketHandler.class:1.4.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
[17:52:19] [main/INFO] [net.minecraft.client.Minecraft]: Stopping!
[17:52:19] [main/INFO] [net.minecraft.client.audio.SoundManager]: SoundSystem shutting down...
[17:52:19] [main/WARN] [net.minecraft.client.audio.SoundManager]: Author: Paul Lamb, www.paulscode.com

**Comment by andjie98** [comment]
game version:  forge1.12.2-2768
Very restrictive platform client

**Comment by KaiKikuchi** [comment]
Hello. Server Redirect is a Forge/Fabric mod. I do not support cloned versions of Forge.
