### ISSUE TITLE
Incompatible with Spigot 1.13.2

### ISSUE THREAD

**Issue by KaiKikuchi** [KaiKikuchi/ServerRedirect#9]
Unfortunately, they are forcing to use a semicolon on the channel name. Hopefully that is compatible with older versions of Minecraft, Spigot, Sponge and Forge, otherwise I will have to find a workaround.
```
[23:57:25 ERROR]: Error occurred while enabling ServerRedirect v1.3.7 (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use ServerRedirect)
	at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:474) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
	at org.bukkit.plugin.messaging.StandardMessenger.registerOutgoingPluginChannel(StandardMessenger.java:180) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
	at net.kaikk.mc.serverredirect.bukkit.ServerRedirect.onEnable(ServerRedirect.java:28) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by KaiKikuchi** [comment]
Fixed in version 1.4
